#!/usr/bin/make -f

#This makefile seems to work in both Windows powershell and Linux bash. Sp this project might not need CMake

all:
	g++ -g -std=c++11 -pthread test_array_reversal.cpp  -o test_array_reversal
